{% set version = "2.32.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rstanarm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rstanarm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstanarm/rstanarm_{{ version }}.tar.gz
  sha256: 911647aeb6bdc303a229fb3a1d7d8fa2e8e01a146e0a6a51b6322d41219cd1fc

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ stdlib('c') }}
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}make
    - {{ posix }}sed
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bh >=1.72.0_2              # [build_platform != target_platform]
    - r-bayesplot >=1.7.0          # [build_platform != target_platform]
    - r-ggplot2 >=2.2.1            # [build_platform != target_platform]
    - r-lme4 >=1.1_8               # [build_platform != target_platform]
    - r-loo >=2.1.0                # [build_platform != target_platform]
    - r-matrix >=1.2_13            # [build_platform != target_platform]
    - r-nlme >=3.1_124             # [build_platform != target_platform]
    - r-rcpp >=0.12.0              # [build_platform != target_platform]
    - r-rcppeigen >=0.3.3.3.0      # [build_platform != target_platform]
    - r-rcppparallel >=5.0.1       # [build_platform != target_platform]
    - r-rstan >=2.26.1             # [build_platform != target_platform]
    - r-rstantools >=2.1.0         # [build_platform != target_platform]
    - r-shinystan >=2.3.0          # [build_platform != target_platform]
    - r-stanheaders >=2.21.0       # [build_platform != target_platform]
    - r-survival >=2.40.1          # [build_platform != target_platform]
  host:
    - r-base
    - r-bh >=1.72.0_2
    - r-bayesplot >=1.7.0
    - r-ggplot2 >=2.2.1
    - r-lme4 >=1.1_8
    - r-loo >=2.1.0
    - r-matrix >=1.2_13
    - r-nlme >=3.1_124
    - r-posterior
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-reformulas
    - r-rstan >=2.32.0
    - r-rstantools >=2.1.0
    - r-shinystan >=2.3.0
    - r-stanheaders >=2.32.0
    - r-survival >=2.40.1
    - tbb-devel                    # [unix]
  run:
    - r-base
    - r-bh >=1.72.0_2
    - r-bayesplot >=1.7.0
    - r-ggplot2 >=2.2.1
    - r-lme4 >=1.1_8
    - r-loo >=2.1.0
    - r-matrix >=1.2_13
    - r-nlme >=3.1_124
    - r-posterior
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-reformulas
    - r-rstan >=2.32.0
    - r-rstantools >=2.1.0
    - r-shinystan >=2.3.0
    - r-stanheaders >=2.32.0
    - r-survival >=2.40.1

test:
  requires:
    - r-codetools
    - r-testthat
    - make
  source_files:
    - tests/
  commands:
    - $R -e "library('rstanarm')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('rstanarm')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]
    

about:
  home: http://discourse.mc-stan.org, http://mc-stan.org/
  dev_url: https://github.com/stan-dev/rstanarm
  doc_url: http://mc-stan.org/rstanarm/
  license: GPL-3.0-or-later
  summary: Estimates previously compiled regression models using the 'rstan' package, which provides the R interface to the Stan C++ library for Bayesian estimation. Users specify models via the customary R syntax with a formula and data.frame plus some additional arguments for priors.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
