{% set version = '2.17.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstanarm
  version: {{ version|replace("-", "_") }}

source:
  fn: rstanarm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rstanarm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstanarm/rstanarm_{{ version }}.tar.gz
  sha256: e01a00144dde9d5d88c5bd23181dae7c670005d9bad28e7eb6681ad9197befab

build:
  merge_build_host: True  # [win]
  number: 2
  # no win64 package for r-shinystan
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh >=1.65.0
    - r-matrix >=1.2_13
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.17.1
    - r-bayesplot >=1.5.0
    - r-ggplot2 >=2.2.1
    - r-lme4 >=1.1_8
    - r-loo >=2.0.0
    - r-nlme >=3.1_124
    - r-rstan >=2.17.2
    - r-rstantools >=1.4.0
    - r-shinystan >=2.3.0
    - r-survival >=2.40.1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh >=1.65.0
    - r-matrix >=1.2_13
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.17.1
    - r-bayesplot >=1.5.0
    - r-ggplot2 >=2.2.1
    - r-lme4 >=1.1_8
    - r-loo >=2.0.0
    - r-nlme >=3.1_124
    - r-rstan >=2.17.2
    - r-rstantools >=1.4.0
    - r-shinystan >=2.3.0
    - r-survival >=2.40.1

test:
  commands:
    - $R -e "library('rstanarm')"           # [not win]
    - "\"%R%\" -e \"library('rstanarm')\""  # [win]

about:
  home: http://discourse.mc-stan.org, http://mc-stan.org/, http://mc-stan.org/rstanarm/
  license: GPL (>= 3)
  summary: Estimates previously compiled regression models using the 'rstan' package, which provides
    the R interface to the Stan C++ library for Bayesian estimation. Users specify models
    via the customary R syntax with a formula and data.frame plus some additional arguments
    for priors.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
