# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pqdJOuHD0vDKhg5TQyk/xndSMsr6DTNY1sAvm78YzphCFPTS24d07CHu2d6V/JkoZr2oaLSOR6Oi9ykCqE9J5spTRvWClTMok8XyfFoLuzudwcFoFVkzcGylMm+W3muk3Ac6A0PnkriDfWQjGG4LP57iLJCt73QFJwBen/4fvKgIgb1XDc8qfuxOxEKuhmSDFPsbqEDwhMmwFdTGDdBDuK1IRWNAOHQKLhj+iHpP+5lDztSS9ysMiIGKqM1BPK2bATXo1YLH2Baz22copSwqOztBsYgH5lArvisa2eh2srV2TKvktRTOnK7GaxeJpJDWaMBZGa6giFgQXAQkET3Zui/J6pCJP5Ruyla899Bc9vI35IiP7zy/9Mjl99XpqoXlau4PZsDD0k0naBobFJKPVd6Enm8HOmD4QvBrELSYBNZn2WQE+NjVp4loegSIOribMDaaQt4rSmsuk4WnQtxDzuLvqyV/7yYoonlgWvkq7AdLIxE95Kj8BhCgwp7KZ9cXI+IK0FlwDzhIYbB6Levs/ZeNTmIH+jqPo+WGqW08Czpn7l8Z1zMdtHrf4P4tFeIJqd0nYPo013UvWTmBvTmu3Eb1OehHj8hH7HYwJwclGQA6/gLHVfX13KsIvl4ttJRd47kzOx/61zcYBjtfDC2m9T4Wb3JoMEizZ8VNkdVmQpE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
