travis:
  secure:
    BINSTAR_TOKEN: pqdJOuHD0vDKhg5TQyk/xndSMsr6DTNY1sAvm78YzphCFPTS24d07CHu2d6V/JkoZr2oaLSOR6Oi9ykCqE9J5spTRvWClTMok8XyfFoLuzudwcFoFVkzcGylMm+W3muk3Ac6A0PnkriDfWQjGG4LP57iLJCt73QFJwBen/4fvKgIgb1XDc8qfuxOxEKuhmSDFPsbqEDwhMmwFdTGDdBDuK1IRWNAOHQKLhj+iHpP+5lDztSS9ysMiIGKqM1BPK2bATXo1YLH2Baz22copSwqOztBsYgH5lArvisa2eh2srV2TKvktRTOnK7GaxeJpJDWaMBZGa6giFgQXAQkET3Zui/J6pCJP5Ruyla899Bc9vI35IiP7zy/9Mjl99XpqoXlau4PZsDD0k0naBobFJKPVd6Enm8HOmD4QvBrELSYBNZn2WQE+NjVp4loegSIOribMDaaQt4rSmsuk4WnQtxDzuLvqyV/7yYoonlgWvkq7AdLIxE95Kj8BhCgwp7KZ9cXI+IK0FlwDzhIYbB6Levs/ZeNTmIH+jqPo+WGqW08Czpn7l8Z1zMdtHrf4P4tFeIJqd0nYPo013UvWTmBvTmu3Eb1OehHj8hH7HYwJwclGQA6/gLHVfX13KsIvl4ttJRd47kzOx/61zcYBjtfDC2m9T4Wb3JoMEizZ8VNkdVmQpE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
